# Generated by Django 5.1 on 2024-08-29 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdocente.sala')),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
