# Generated by Django 5.0.7 on 2024-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocente', '0001_add_reserva2_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva2',
            name='estado',
            field=models.IntegerField(db_column='ESTADOS'),
        ),
    ]
