# Generated by Django 5.0.7 on 2024-11-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocente', '0002_add_reserva2_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recintos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo_recurso', models.CharField(db_column='tipo_recurso', max_length=100)),
                ('sala', models.CharField(db_column='sala', max_length=100)),
                ('nombre_recinto', models.CharField(db_column='nombre_recinto', max_length=100)),
                ('capacidad', models.IntegerField(db_column='capacidad')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_final', models.DateField(db_column='fecha_final')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_final', models.TimeField(db_column='hora_final')),
                ('cantidad_modulos', models.IntegerField(db_column='cantidad_modulos')),
                ('denominacion_evento', models.CharField(db_column='denominacion_evento', max_length=100)),
                ('id_evento', models.IntegerField(db_column='id_evento')),
                ('id_recurso', models.IntegerField(db_column='id_recurso')),
            ],
            options={
                'db_table': 'recintos',
            },
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='recinto',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.RemoveField(
            model_name='recinto',
            name='id_sede',
        ),
        migrations.RemoveField(
            model_name='recinto',
            name='id_tipo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_recinto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='reserva2',
            name='estado',
            field=models.IntegerField(db_column='ESTADO'),
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='TipoRecinto',
        ),
        migrations.DeleteModel(
            name='Recinto',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
