# Generated by Django 4.2.13 on 2024-08-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocente', '0002_remove_evento_horario_remove_evento_sala_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='descripcion',
            new_name='denominacion_evento',
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_sala',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
