# Generated by Django 5.1 on 2024-09-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdocente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Coordinador General Docente', 'Coordinador General Docente'), ('Coordinadora Docente', 'Coordinadora Docente'), ('Asistente de Coordinación Docente', 'Asistente de Coordinación Docente')], max_length=50),
        ),
    ]
